---
- fail:
    msg:
    - "kubernetes_master_kubeadm_config has been moved. It is now located at kubernetes_common_kubeadm_config."
    - "Please update your inventories"
  when: kubernetes_master_kubeadm_config is defined

- name: generate a kubeadm token
  command: "/usr/bin/kubeadm token create --config /etc/kubernetes/kubeadm.conf --kubeconfig /etc/kubernetes/admin.conf"
  register: generated_token
  run_once: True
  delegate_to: "{{ groups['primary_master']|first }}"

- include_tasks: install.yml
  when: wardroom_action == 'install'

- include_tasks: upgrade.yml
  when: wardroom_action == 'upgrade'
